/*
# Add private user appearance assets

1. New columns
- `user_settings.avatar_path`: private storage path for the signed-in user's profile picture.
- `user_settings.background_path`: private storage path for the signed-in user's custom background image.
- `user_settings.custom_colors`: JSON object containing validated user-selected appearance colors.

2. Storage
- Create the private `user-assets` bucket.
- Limit stored files to image MIME types and 10 MiB per file.
- Store each user's files beneath their auth user ID.

3. Security
- Keep the bucket private; the client uses short-lived signed URLs.
- Add separate SELECT, INSERT, UPDATE, and DELETE policies for `storage.objects`.
- Every storage policy checks that the first path segment equals `auth.uid()`.
- Existing owner-scoped `user_settings` policies continue to protect the new columns.

4. Important notes
- File names are generated by the app from the validated MIME type; original filenames are not trusted.
- Existing user settings and files are not removed or renamed.
*/

ALTER TABLE public.user_settings
  ADD COLUMN IF NOT EXISTS avatar_path text,
  ADD COLUMN IF NOT EXISTS background_path text,
  ADD COLUMN IF NOT EXISTS custom_colors jsonb NOT NULL DEFAULT '{}'::jsonb;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'user-assets',
  'user-assets',
  false,
  10485760,
  ARRAY['image/png', 'image/jpeg', 'image/webp']::text[]
)
ON CONFLICT (id) DO UPDATE
SET public = false,
    file_size_limit = 10485760,
    allowed_mime_types = ARRAY['image/png', 'image/jpeg', 'image/webp']::text[];

DROP POLICY IF EXISTS "user_assets_select_own" ON storage.objects;
CREATE POLICY "user_assets_select_own"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'user-assets'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "user_assets_insert_own" ON storage.objects;
CREATE POLICY "user_assets_insert_own"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'user-assets'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "user_assets_update_own" ON storage.objects;
CREATE POLICY "user_assets_update_own"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'user-assets'
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'user-assets'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "user_assets_delete_own" ON storage.objects;
CREATE POLICY "user_assets_delete_own"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'user-assets'
  AND (storage.foldername(name))[1] = auth.uid()::text
);